# Generated by Django 4.1 on 2022-08-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(blank=True, max_length=30, null=True, verbose_name='Məhsul')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sorğu nömrəsi')),
                ('user_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Müştəri İD')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Təklifin qüvvədə olduğu müddət')),
                ('valyuta', models.CharField(blank=True, choices=[('azn', 'AZN'), ('usd', 'USD'), ('eur', 'EUR'), ('try', 'TRY'), ('rub', 'RUB')], default='azn', max_length=10, null=True, verbose_name='Valyuta')),
                ('miqdar', models.CharField(blank=True, max_length=10, null=True, verbose_name='Miqdar')),
                ('price', models.CharField(blank=True, max_length=10, null=True, verbose_name='Vahidin qiyməti')),
                ('edv_degree', models.CharField(blank=True, max_length=10, null=True, verbose_name='ƏDV drərəcəsi')),
                ('edv_price', models.CharField(blank=True, max_length=10, null=True, verbose_name='ƏDV məbləği')),
                ('payment_terms', models.TextField(blank=True, choices=[('öncədən ödəniş', 'ÖNCƏDƏN ÖDƏNİŞ'), ('konsiqnasiya', 'KONSİQNASİYA')], default='konsiqnasiya', max_length=14, null=True, verbose_name='Ödəniş şərti')),
                ('bank_account', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bank hesabı')),
                ('discount', models.CharField(blank=True, choices=[('var', 'VAR'), ('yoxdur', 'YOXDUR')], default='var', max_length=10, null=True, verbose_name='Endirim')),
                ('delivery_condition', models.TextField(blank=True, choices=[('exw', 'EXW'), ('fca', 'FCA'), ('fob', 'FOB'), ('cif', 'CIF')], default='fca', max_length=4, null=True, verbose_name='Çatdırılma şərti')),
                ('country', models.TextField(blank=True, null=True, verbose_name='Ölkə')),
                ('city', models.TextField(blank=True, null=True, verbose_name='Şəhər')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Ünvan')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip kod')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Çatdırılma tarixi')),
                ('delivery_cost', models.CharField(blank=True, max_length=10, null=True, verbose_name='Çatdırılma xərci')),
                ('type_transport', models.CharField(blank=True, choices=[('avtomobil', 'AVTOMOBİL'), ('dəmir yolu', 'DƏMİR YOLU'), ('dəniz', 'DƏNİZ'), ('hava', 'HAVA')], default='avtomobil', max_length=10, null=True, verbose_name='Çatdırılma xərci')),
                ('status', models.BooleanField(default=False, verbose_name='Qaralama')),
                ('tesdiq', models.BooleanField(default=False, verbose_name='Təsdiq gözlənilir')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mehsul', to='post.product', verbose_name='Məhsul')),
            ],
        ),
    ]
