# Generated by Django 4.1 on 2022-08-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_status_task_qaralama'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='qaralama',
            field=models.BooleanField(default=True, verbose_name='Qaralama'),
        ),
    ]
