# Generated by Django 4.1 on 2022-08-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, null=True, unique=True),
        ),
    ]
