# Generated by Django 4.1 on 2022-08-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
